compatibility_date = "2022-12-23"

name = "clip-web"
workers_dev = false

main = ".cloudflare/worker.js"

[site]
bucket = ".cloudflare/public"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = ".cloudflare"
main = "worker.js"

[miniflare]
host = "clip.localhost"
port = 3000
routes = [{ pattern = "clip.localhost:3000/*" }]
