compatibility_date = "2022-12-23"

name = "clip-image-get"
workers_dev = false

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./dist"
main = "./main.mjs"

[[kv_namespaces]]
binding = "clipData"
id = "ef6ddb45fac643a4847ba5e6dd888a9d" # clip

[miniflare]
host = "api.localhost"
port = 3000
routes = [{ pattern = "api.localhost:3000/clip-image-get*" }]
